spring:
  datasource:
    driver-class-name: com.clickhouse.jdbc.ClickHouseDriver
    url: ${url:jdbc:clickhouse://10.151.0.15:8123/saas_shoplus_analysis?allow_multiple_queries=true&query_settings=allow_multi_statements=1&allowMultiQueries=true}
    username: ${user:admin}
    password: ${pw:gPXaYNwQv1PsJuG}

server:
  port: 8080

logging:
  level:
    com.clickhouse: DEBUG
